services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - mongodb

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: EcoRide2
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: Tounsia
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mysql-data:
  mongodb-data:
